### ISSUE TITLE
vite下静态资源打包时有问题

### ISSUE THREAD

**Issue by DCLangX** [ykfe/ssr#142]
## 详细描述你的问题
昨天启了vite+vue3+nestjs的项目，纯vite打包，开发模式静态资源都挺好的，都能显示，但是在打包后静态资源就不能显示了
尝试了public文件夹和vite引入的方式均无法显示
```
<img src="/public/company-logo.png">
<img src="@/assets/img/upgrade1.jpg">
```
如图

![1](https://user-images.githubusercontent.com/19513657/145136768-d6c9a87d-6b7a-4cb5-87d1-8cd9b7afe9c4.png)

打包后网页中1，2，3均不能显示，离奇的是，3和4好像没什么区别，但是4能显示

![2](https://user-images.githubusercontent.com/19513657/145136862-aa5c6b28-54af-4bf1-a049-f50df1d80930.png)

这是实际打包后的资源

![3](https://user-images.githubusercontent.com/19513657/145136921-f46b6628-fbda-4a6b-8e02-960c6749ba56.jpg)

可以看到标记1的`company-logo.png`明明只在`/public`引用了一次，却被打包出三个文件，但是仍然最后还是不能正常显示
```
/client/company-logo.8bc7bc60.chunk.png
/client/company-logo.8bc7bc60.png
/server/company-logo.png
```
## 期望的结果
静态资源打包后正常显示

## 当前使用的版本

使用的6.1.18最新版本

**Comment by zhangyuang** [comment]
打包问题晚点看看，不过静态资源推荐直接放node静态资源文件夹不需要打包

**Comment by DCLangX** [comment]
> 静态资源直接放node静态资源文件夹不需要打包

是的，我试了放在`/build`下面，发现打包的时候里面的文件夹会被清空，导致vite打包时出错，只有`/public`才没被处理可以打包

**Comment by zhangyuang** [comment]
就是推荐放public



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 爱吃薯片的内存条 ***@***.***&gt;
发送时间: 2021年12月8日 10:50
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zhangyuang/ssr] vite下静态资源打包时有问题 (Issue #142)





  
静态资源直接放node静态资源文件夹不需要打包
  
是的，我试了放在/build下面，发现打包的时候里面的文件夹会被清空，导致vite打包时出错，只有/public才没被处理可以打包
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangyuang** [comment]
public文件夹放文件直接`/images` 绝对路径使用

**Comment by DCLangX** [comment]
> public文件夹放文件直接`/images` 绝对路径使用

emmm....这个我明白，我上面1应该就是这么做的好像，public文件夹里放了一个`company-logo.png`，然后代码里
```
<img src="/public/company-logo.png">
```
不过打包后被生成了
```
<img src="/assets/company-logo.8bc7bc60.png" data-v-8357fbd6="">
```

**Comment by zhangyuang** [comment]
那你先用webpack打包吧



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 爱吃薯片的内存条 ***@***.***&gt;
发送时间: 2021年12月8日 11:42
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zhangyuang/ssr] vite下静态资源打包时有问题 (Issue #142)





  
public文件夹放文件直接/images 绝对路径使用
  
emmm....这个我明白，我上面1应该就是这么做的好像，public文件夹里放了一个company-logo.png，然后代码里
 <img src="/public/company-logo.png"&gt;  
不过打包后被生成了
 <img src="/assets/company-logo.8bc7bc60.png" data-v-8357fbd6=""&gt;  
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangyuang** [comment]
放public下引入没有任何问题，是/company-logo.png不是/public/company-logo.png

**Comment by DCLangX** [comment]
> 放public下引入没有任何问题，是/company-logo.png不是/public/company-logo.png

感谢，理解错意思了，试了下，确实这样可以

**Comment by zhangyuang** [comment]
close by https://github.com/zhangyuang/ssr/commit/698a18c1ed0ebd7d449cde88aaff86b17036ee3c
