### ISSUE TITLE
关于nestjs-vue3-ssr 模板使用ant-design-vue 的问题反馈

### ISSUE THREAD

**Issue by canyuegongzi** [ykfe/ssr#147]
## 项目使用

项目中按照文档中说明的直接安装使用。
![eeb94705282dfe426e827b8bab73f69](https://user-images.githubusercontent.com/32031360/145843251-6820e860-f69c-4cc0-874e-bd0cec787cb1.png)

## 错误

![6f0a3fdb17b83d7607ba1d7ea20a7f7](https://user-images.githubusercontent.com/32031360/145843321-a14bd72e-3879-4a7f-b69f-0f294ac71123.png)

希望大佬能给解一下疑惑，感谢。

**Comment by zhangyuang** [comment]
即没装依赖也没引入组件...



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ***@***.*** ***@***.***&gt;
发送时间: 2021年12月13日 23:48
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 关于nestjs-vue3-ssr 模板使用ant-design-vue 的问题反馈 (Issue #147)





 
项目使用
 
项目中按照文档中说明的直接安装使用。
 
 
错误
 

 
希望大佬能给解一下疑惑，感谢。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by canyuegongzi** [comment]
> 即没装依赖也没引入组件... 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: ***@***.*** ***@***.***&gt; 发送时间: 2021年12月13日 23:48 收件人: zhangyuang/ssr ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [zhangyuang/ssr] 关于nestjs-vue3-ssr 模板使用ant-design-vue 的问题反馈 (Issue #147) 项目使用 项目中按照文档中说明的直接安装使用。 错误 希望大佬能给解一下疑惑，感谢。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

问题解决了，是babel配置文件中手动配置按需引入的问题

**Comment by zhangyuang** [comment]
不需要配babel啊。。都帮你配完了

**Comment by zhangyuang** [comment]
你这个错误很明显你压根就没有引入组件
