### ISSUE TITLE
html标签会添加一个“font-size: 512px;”的样式

### ISSUE THREAD

**Issue by linchCN** [ykfe/ssr#203]
html标签会添加一个“font-size: 512px;”的样式，会影响样式，请问如何这个如何设置
<img width="794" alt="image" src="https://user-images.githubusercontent.com/21193805/171364510-f34641b8-bb10-42d0-8fe7-bf50271c0f35.png">

**Comment by zhangyuang** [comment]
不需要可自行移除remInitial



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: linchCN ***@***.***&gt;
发送时间: 2022年6月1日 16:45
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangyuang/ssr] html标签会添加一个“font-size: 512px;”的样式 (Issue #203)





 
html标签会添加一个“font-size: 512px;”的样式，会影响样式，请问如何这个如何设置

**Comment by linchCN** [comment]
> 不需要可自行移除remInitial 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: linchCN ***@***.***&gt; 发送时间: 2022年6月1日 16:45 收件人: zhangyuang/ssr ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [zhangyuang/ssr] html标签会添加一个“font-size: 512px;”的样式 (Issue #203) html标签会添加一个“font-size: 512px;”的样式，会影响样式，请问如何这个如何设置 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

搜索代码并未找到remInitial关键字，
/components/layout/index.tsx 里面也并未找到，请问在哪里设置

**Comment by zhangyuang** [comment]
react直接删除layout里面跟fontsize有关代码



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: linchCN ***@***.***&gt;
发送时间: 2022年6月1日 16:51
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zhangyuang/ssr] html标签会添加一个“font-size: 512px;”的样式 (Issue #203)





  
不需要可自行移除remInitial 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: linchCN @.&gt; 发送时间: 2022年6月1日 16:45 收件人: zhangyuang/ssr @.&gt; 抄送: Subscribed @.&gt; 主题: Re: [zhangyuang/ssr] html标签会添加一个“font-size: 512px;”的样式 (Issue #203) html标签会添加一个“font-size: 512px;”的样式，会影响样式，请问如何这个如何设置 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
搜索代码并未找到remInitial关键字，
 /components/layout/index.tsx 里面也并未找到，请问在哪里设置

**Comment by linchCN** [comment]
> react直接删除layout里面跟fontsize有关代码 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: linchCN ***@***.***&gt; 发送时间: 2022年6月1日 16:51 收件人: zhangyuang/ssr ***@***.***&gt; 抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [zhangyuang/ssr] html标签会添加一个“font-size: 512px;”的样式 (Issue #203) 不需要可自行移除remInitial 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: linchCN @.&gt; 发送时间: 2022年6月1日 16:45 收件人: zhangyuang/ssr @.&gt; 抄送: Subscribed @.&gt; 主题: Re: [zhangyuang/ssr] html标签会添加一个“font-size: 512px;”的样式 (Issue #203) html标签会添加一个“font-size: 512px;”的样式，会影响样式，请问如何这个如何设置 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; 搜索代码并未找到remInitial关键字， /components/layout/index.tsx 里面也并未找到，请问在哪里设置 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

不好意思，不是很清楚您说的意思。demo里面也没有找到fontSize关键字

**Comment by zhangyuang** [comment]
<img width="894" alt="image" src="https://user-images.githubusercontent.com/17424434/171369127-ac0a821a-0e69-4174-ad1e-12af995ae933.png">

**Comment by linchCN** [comment]
> <img alt="image" width="894" src="https://user-images.githubusercontent.com/17424434/171369127-ac0a821a-0e69-4174-ad1e-12af995ae933.png">

好的，已解决
