### ISSUE TITLE
怎么使用自己开发的客户端和服务端插件？

### ISSUE THREAD

**Issue by HQHC** [ykfe/ssr#341]
提问前请确认以下几点信息，否则你的问题将不会被解答

- 参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式
- 确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案
- 对应服务端框架的使用问题请去它们的官方文档找答案。例如 [Midway](https://midwayjs.org/), [Nest.js](https://nestjs.com/)
- 如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭
- 原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 Google 找答案而不是在这里。

## 当前使用的版本

`不要贴 package.json 用 yarn list "ssr*" ` 来查看版本。同时建议熟读[semver](https://semver.org/) 规则并且知道怎么安装最新依赖！

## 复现仓库地址

超过一行代码能描述的问题必须提供复现地址, 用默认的 `example` 给最简单的复现代码不要给包含着一堆业务代码的仓库

**Comment by zhangyuang** [comment]
不再推荐自行开发新的插件，需要适配的点比较多。官方插件足够cover 所有场景

**Comment by HQHC** [comment]
React 带有内置优化，例如 流式服务器渲染（Streaming Server Rendering） 和 Selective Hydration，它们已经与 Suspense 集成。参见 [架构概述](https://github.com/reactwg/react-18/discussions/37) 并观看 [技术讲座](https://www.youtube.com/watch?v=pj5N-Khihgc) 以了解更多。

这个特性还不支持吧？

**Comment by zhangyuang** [comment]
目前没有支持，这是一个不成熟且意义不大的特性



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: HQHC ***@***.***&gt;
发送时间: 2024年11月21日 18:12
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 怎么使用自己开发的客户端和服务端插件？ (Issue #341)





 
React 带有内置优化，例如 流式服务器渲染（Streaming Server Rendering） 和 Selective Hydration，它们已经与 Suspense 集成。参见 架构概述 并观看 技术讲座 以了解更多。
 
这个特性还不支持吧？

**Comment by HQHC** [comment]
> 目前没有支持，这是一个不成熟且意义不大的特性 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: HQHC ***@***.***&gt; 发送时间: 2024年11月21日 18:12 收件人: zhangyuang/ssr ***@***.***&gt; 抄送: yuuang ***@***.***&gt;, State change ***@***.***&gt; 主题: Re: [zhangyuang/ssr] 怎么使用自己开发的客户端和服务端插件？ (Issue #341) React 带有内置优化，例如 流式服务器渲染（Streaming Server Rendering） 和 Selective Hydration，它们已经与 Suspense 集成。参见 架构概述 并观看 技术讲座 以了解更多。 这个特性还不支持吧？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

这个解决ssr时ttfb过长很有效果吧？

**Comment by zhangyuang** [comment]
解决ttfb有很多方案，可以用部分csr渲染ssr只渲染首屏。就算是全量渲染也很少会遇到ttfb过长的问题，ttfb时间长90%的原因是业务代码写得太烂



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: HQHC ***@***.***&gt;
发送时间: 2024年11月21日 18:15
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 怎么使用自己开发的客户端和服务端插件？ (Issue #341)





  
目前没有支持，这是一个不成熟且意义不大的特性 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: HQHC @.&gt; 发送时间: 2024年11月21日 18:12 收件人: zhangyuang/ssr @.&gt; 抄送: yuuang @.&gt;, State change @.&gt; 主题: Re: [zhangyuang/ssr] 怎么使用自己开发的客户端和服务端插件？ (Issue #341) React 带有内置优化，例如 流式服务器渲染（Streaming Server Rendering） 和 Selective Hydration，它们已经与 Suspense 集成。参见 架构概述 并观看 技术讲座 以了解更多。 这个特性还不支持吧？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
这个解决ssr时ttfb过长很有效果吧？

**Comment by HQHC** [comment]
首屏接口耗时比较长，服务端请求时ttfb长，比较常见吧，还没到业务代码呢

**Comment by zhangyuang** [comment]
那就去优化接口耗时或者分拆接口。一堆解决方案没必要选一个吃力不讨好的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: HQHC ***@***.***&gt;
发送时间: 2024年11月21日 18:21
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 怎么使用自己开发的客户端和服务端插件？ (Issue #341)





 
首屏接口耗时比较长，服务端请求时ttfb长，比较常见吧，还没到业务代码呢

**Comment by HQHC** [comment]
吃力不讨好吗？  这remix、nextjs也在做这方面的东西啊，有状态的渐进性页面加载。

**Comment by zhangyuang** [comment]
搜搜相关信息就知道suspense ssr的bug和breaking change有多少了。
我的观点是业务瓶颈绝大部分情况都不在 renderToxxx方法上

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: HQHC ***@***.***&gt;
发送时间: 2024年11月21日 18:26
收件人: zhangyuang/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [zhangyuang/ssr] 怎么使用自己开发的客户端和服务端插件？ (Issue #341)





 
吃力不讨好吗？  这remix、nextjs也在做这方面的东西啊，有状态的渐进性页面加载。
