### ISSUE TITLE
接入微软fluentUI组件库问题

### ISSUE THREAD

**Issue by XYjourney** [ykfe/ssr#95]
提问前请确认以下几点信息，否则你的问题将不会被解答

- 参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式
- 确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案
- 对应服务端框架的使用问题请去它们的官方文档找答案。例如 [Midway](https://midwayjs.org/), [Nest.js](https://nestjs.com/)
- 如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭
- 原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 google找答案而不是在这里。

## 详细描述你的问题
希望在框架里引入 https://developer.microsoft.com/ja-jp/fluentui#/， 但是在引用后，会有错误，具体来讲，我在app.ts文件里
![image](https://user-images.githubusercontent.com/18476675/129517656-13ecc9ad-ef3c-4919-87a0-9eb7173aa19b.png)
设置fluentUI的ssr flag，然后成功渲染，但是当我f5刷新时，报
![image](https://user-images.githubusercontent.com/18476675/129517470-b62472a5-0d9c-4b25-897c-d0cdead4c98b.png)

## 期望的结果
能够成功在ssr中渲染响应组件

## 当前使用的版本
![image](https://user-images.githubusercontent.com/18476675/129517441-10b36628-2df4-4651-84a7-9c3e4eacf258.png)

## 你本人对问题可能的原因判断(如果你能大概判断的话)
![image](https://user-images.githubusercontent.com/18476675/129517470-b62472a5-0d9c-4b25-897c-d0cdead4c98b.png)

**Comment by zhangyuang** [comment]
1、报的错是这个组件没办法在服务端渲染
2、完全不需要用这个什么 setSSR(true)。。。
3、自行参考文档 http://doc.ssr-fc.com/docs/features$faq#%E4%BD%BF%E7%94%A8%20UI%20%E6%A1%86%E6%9E%B6
4、如果你觉得对你来说太困难的话，请直接用antd或者vant这些框架已经帮你适配好的ui框架

**Comment by zhangyuang** [comment]
如何让某个组件只在客户端渲染：http://doc.ssr-fc.com/docs/features$faq#%E5%A6%82%E4%BD%95%E8%AE%A9%E6%9F%90%E4%B8%AA%E7%BB%84%E4%BB%B6%E5%8F%AA%E5%9C%A8%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%B8%B2%E6%9F%93

**Comment by XYjourney** [comment]
react组件是可以在服务端渲染 只不过这套组件设置了一些判断 我仔细看了一下 咱们的框架会在window里塞一些东西 我如果想扩展这个window 要怎么做？

**Comment by zhangyuang** [comment]
不要去扩展window，需要扩展window就说明你的使用方式是错误的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: XYjourney ***@***.***&gt;
发送时间: 2021年8月17日 10:49
收件人: ykfe/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ykfe/ssr] 接入微软fluentUI组件库问题 (#95)





 
react组件是可以在服务端渲染 只不过这套组件设置了一些判断 我仔细看了一下 咱们的框架会在window里塞一些东西 我如果想扩展这个window 要怎么做？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XYjourney** [comment]
本来setSSR是为了避免上面那个报错的，但是没生效，setSSR是fluentUI里提供的api，具体原因我还在调查。
![image](https://user-images.githubusercontent.com/18476675/129656471-6683b4bf-678d-496b-985f-2a849d030fcb.png)

![image](https://user-images.githubusercontent.com/18476675/129656393-5024a44c-f458-4bd5-a7bb-dd5910923488.png)
![image](https://user-images.githubusercontent.com/18476675/129656719-ba4a464c-bde4-4b37-84e1-53f0c6576e69.png)

源码里有这条判断，但是我们server端运行时是有这个window对象,所以最后抛错了

**Comment by XYjourney** [comment]
fluentUI在next.js里是支持的，咱们这边能不能也支持一下

**Comment by zhangyuang** [comment]
我来解决那肯定可以搞得定，不过还是建议你直接用antd，antd层面框架已经做了很多优化



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: XYjourney ***@***.***&gt;
发送时间: 2021年8月17日 10:55
收件人: ykfe/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ykfe/ssr] 接入微软fluentUI组件库问题 (#95)





 
fluentUI在next.js里是支持的，咱们这边能不能也支持一下
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XYjourney** [comment]
我明白你的意思 主要fluentUI是我们公司选定的框架 其他项目也在使用 很多组件都有依赖

**Comment by zhangyuang** [comment]
有空看看，这两天会比较忙



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: XYjourney ***@***.***&gt;
发送时间: 2021年8月17日 10:58
收件人: ykfe/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ykfe/ssr] 接入微软fluentUI组件库问题 (#95)





 
我明白你的意思 主要fluentUI是我们公司选定的框架 其他项目也在使用 很多组件都有依赖
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XYjourney** [comment]
好的 谢谢 
![image](https://user-images.githubusercontent.com/18476675/129656894-e6c46f2b-68a6-440f-af26-006f2ae4362f.png)
主要也是这条 它没判断window.navigator是否存在

**Comment by zhangyuang** [comment]
他只判断window是否存在的肯定是不准确的。mock window在服务端很常见。需要做更精确的判断是否在服务端环境



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: XYjourney ***@***.***&gt;
发送时间: 2021年8月17日 11:00
收件人: ykfe/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ykfe/ssr] 接入微软fluentUI组件库问题 (#95)





 
好的 谢谢
 
 主要也是这条 它没判断window.navigator是否存在
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XYjourney** [comment]
是的 但是那个setSSR没生效 确实我不知道为啥

**Comment by zhangyuang** [comment]
你应该在controller里面加这行代码



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: XYjourney ***@***.***&gt;
发送时间: 2021年8月17日 11:08
收件人: ykfe/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ykfe/ssr] 接入微软fluentUI组件库问题 (#95)





 
是的 但是那个setSSR没生效 确实我不知道为啥
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XYjourney** [comment]
![image](https://user-images.githubusercontent.com/18476675/129669945-df2ecac4-e799-4413-ad39-4f27b716926a.png)
同样的报错

**Comment by zhangyuang** [comment]
直接引入并没有任何问题。。根本不需要什么 setSSR。。。如果这个ui库还要额外设置`setSSR` 这种东西也太low了。
不过国外的ui基本用的方案是 css in js 的方案。ssr下样式会闪烁，比较难处理，我也不想处理这种方案。至于它官方给的ssr guide简直是在瞎搞，侵入性太大不可能这么去干。
综上，不要用这个，非要用的话目前不支持

**Comment by XYjourney** [comment]
ok 直接引入你那里确定没问题吗 不应该啊

**Comment by zhangyuang** [comment]
你有问题就给复现，也有可能是特别的组件有问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: XYjourney ***@***.***&gt;
发送时间: 2021年8月20日 14:03
收件人: ykfe/ssr ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ykfe/ssr] 接入微软fluentUI组件库问题 (#95)





 
ok 直接引入你那里确定没问题吗 不应该啊
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
